# This workflow deploy the packages to Maven Central

name: Build and ship to Maven Central

#on:
#    push:
#        tags:
#            - "v*"
on:
    release:
        types: [released]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v3
              with:
                  java-version: 11
                  server-id: ossrh
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
                  gpg-passphrase: MAVEN_GPG_PASSPHRASE
            - name: Publish package
              run: mvn --batch-mode -Prelease-sign-artifacts clean deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
                  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
